# Generated by Django 6.0.6 on 2026-07-07 15:42

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('courses', '0001_initial'),
        ('students', '0002_studentfeedback_urgency'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentfeedback',
            options={'ordering': ['-submitted_at']},
        ),
        migrations.AddField(
            model_name='studentfeedback',
            name='submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_feedback', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='studentfeedback',
            name='category',
            field=models.CharField(choices=[('complaint', 'Complaint'), ('suggestion', 'Suggestion'), ('inquiry', 'Inquiry'), ('academic', 'Academic'), ('support', 'Support'), ('other', 'Other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='studentfeedback',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('resolved', 'Resolved')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='studentfeedback',
            name='urgency',
            field=models.CharField(choices=[('normal', 'Normal'), ('high', 'High'), ('critical', 'Critical')], default='normal', max_length=20),
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matric_number', models.CharField(max_length=40, unique=True, validators=[django.core.validators.RegexValidator(message='Matric number may contain only letters, numbers, slash, underscore, and hyphen.', regex='^[A-Za-z0-9/_-]+$')])),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('programme', models.CharField(max_length=160)),
                ('level', models.CharField(choices=[('100', '100 Level'), ('200', '200 Level'), ('300', '300 Level'), ('400', '400 Level'), ('500', '500 Level'), ('PG', 'Postgraduate')], max_length=10)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('suspended', 'Suspended'), ('graduated', 'Graduated')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('courses', models.ManyToManyField(blank=True, related_name='enrolled_students', to='courses.course')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='students', to='core.department')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='students', to='core.faculty')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_record', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['matric_number'],
            },
        ),
    ]
