# Generated by Django 6.0.6 on 2026-07-07 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_studentfeedback_urgency'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentfeedback',
            name='student_email',
            field=models.EmailField(blank=True, default='', max_length=254, null=True),
        ),
    ]
