# Generated by Django 6.0.6 on 2026-07-07 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_studentfeedback_student_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentfeedback',
            name='classification',
            field=models.CharField(default='academic', max_length=50),
        ),
    ]
