# Generated by Django 6.0.6 on 2026-07-07 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_alter_studentfeedback_options_and_more'),
        ('students', '0004_studentfeedback_classification'),
    ]

    operations = [
    ]
