# Generated by Django 6.0.6 on 2026-07-07 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_merge_20260707_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentfeedback',
            name='classification',
            field=models.CharField(choices=[('academic', 'Academic'), ('administrative', 'Administrative'), ('facility', 'Facility'), ('welfare', 'Welfare'), ('other', 'Other')], default='academic', max_length=50),
        ),
    ]
