# Generated by Django 6.0.6 on 2026-07-07 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_studentfeedback_admin_comment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentfeedback',
            name='submission_mode',
            field=models.CharField(blank=True, choices=[('anonymous', 'Anonymous'), ('confidential', 'Confidential'), ('open_identity', 'Open_Identity')], default='open_identity', max_length=50),
        ),
        migrations.AlterField(
            model_name='studentfeedback',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('under_review', 'Under Review'), ('resolved', 'Resolved')], default='pending', max_length=30),
        ),
        migrations.AlterField(
            model_name='studentfeedbackupdate',
            name='new_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('under_review', 'Under Review'), ('resolved', 'Resolved')], max_length=30),
        ),
        migrations.AlterField(
            model_name='studentfeedbackupdate',
            name='previous_status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('under_review', 'Under Review'), ('resolved', 'Resolved')], max_length=30),
        ),
    ]
