# Generated by Django 6.0.6 on 2026-07-08 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0008_studentfeedback_submission_mode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentfeedback',
            name='category',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='studentfeedback',
            name='classification',
            field=models.CharField(default='academic', max_length=50),
        ),
        migrations.AlterField(
            model_name='studentfeedback',
            name='status',
            field=models.CharField(default='pending', max_length=30),
        ),
        migrations.AlterField(
            model_name='studentfeedback',
            name='submission_mode',
            field=models.CharField(blank=True, default='open_identity', max_length=50),
        ),
        migrations.AlterField(
            model_name='studentfeedback',
            name='urgency',
            field=models.CharField(default='normal', max_length=20),
        ),
    ]
