# Generated by Django 6.0.6 on 2026-07-09 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0010_studentfeedbackattachment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StudentFeedbackAttachment',
        ),
    ]
