# Generated by Django 6.0.6 on 2026-07-09 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0011_delete_studentfeedbackattachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentfeedback',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('under_review', 'Under Review'), ('resolved', 'Resolved')], default='pending', max_length=30),
        ),
    ]
