# Generated by Django 6.0.6 on 2026-07-09 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kpi',
            name='category',
            field=models.CharField(default='academic', max_length=255),
        ),
    ]
