# Generated by Django 6.0.6 on 2026-07-06 17:07

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InstitutionalDocumentCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=160, unique=True)),
                ('slug', models.SlugField(max_length=180, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='InstitutionalDocumentTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='InstitutionalDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=280, unique=True)),
                ('document_type', models.CharField(choices=[('pdf', 'PDF'), ('word', 'Word'), ('powerpoint', 'PowerPoint'), ('spreadsheet', 'Spreadsheet'), ('image', 'Image'), ('link', 'Link'), ('other', 'Other')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('related_module', models.CharField(choices=[('general_dqa', 'General DQA'), ('accreditation', 'Accreditation'), ('qa_committee', 'QA Committee'), ('student_assessment', 'Student Assessment'), ('examination_quality', 'Examination Quality'), ('student_complaints', 'Student Complaints'), ('lecture_monitoring', 'Lecture Monitoring'), ('service_delivery', 'Service Delivery'), ('institutional_policy', 'Institutional Policy'), ('platform_documentation', 'Platform Documentation')], max_length=40)),
                ('visibility_level', models.CharField(choices=[('private', 'Private'), ('dqa_only', 'DQA Only'), ('qa_focal_persons', 'QA Focal Persons'), ('hods_and_deans', 'HODs and Deans'), ('committee_members', 'Committee Members'), ('all_authenticated', 'All Authenticated Users'), ('public', 'Public')], max_length=40)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending_review', 'Pending Review'), ('approved', 'Approved'), ('published', 'Published'), ('rejected', 'Rejected'), ('archived', 'Archived'), ('expired', 'Expired')], default='draft', max_length=30)),
                ('owner', models.CharField(blank=True, max_length=160)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('effective_date', models.DateField(blank=True, null=True)),
                ('review_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('is_latest', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_documents', to=settings.AUTH_USER_MODEL)),
                ('published_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='published_documents', to=settings.AUTH_USER_MODEL)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='documents.institutionaldocumentcategory')),
                ('tags', models.ManyToManyField(blank=True, related_name='documents', to='documents.institutionaldocumenttag')),
            ],
            options={
                'ordering': ['-created_at', 'title'],
            },
        ),
        migrations.CreateModel(
            name='InstitutionalDocumentVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.CharField(max_length=30)),
                ('file', models.FileField(blank=True, null=True, upload_to='institutional_documents/')),
                ('external_url', models.URLField(blank=True)),
                ('file_name', models.CharField(blank=True, max_length=255)),
                ('file_size', models.PositiveBigIntegerField(blank=True, null=True)),
                ('mime_type', models.CharField(blank=True, max_length=120)),
                ('checksum', models.CharField(blank=True, max_length=64)),
                ('change_summary', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending_review', 'Pending Review'), ('approved', 'Approved'), ('published', 'Published'), ('rejected', 'Rejected'), ('archived', 'Archived'), ('expired', 'Expired')], default='draft', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='documents.institutionaldocument')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InstitutionalDocumentReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision', models.CharField(choices=[('approved', 'Approved'), ('rejected', 'Rejected'), ('returned_for_correction', 'Returned for Correction')], max_length=30)),
                ('comment', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='documents.institutionaldocument')),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='documents.institutionaldocumentversion')),
            ],
            options={
                'ordering': ['-reviewed_at'],
            },
        ),
        migrations.CreateModel(
            name='InstitutionalDocumentAccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('viewed', 'Viewed'), ('downloaded', 'Downloaded'), ('previewed', 'Previewed')], max_length=20)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('accessed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_logs', to='documents.institutionaldocument')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='access_logs', to='documents.institutionaldocumentversion')),
            ],
            options={
                'ordering': ['-accessed_at'],
            },
        ),
        migrations.AddField(
            model_name='institutionaldocument',
            name='current_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_for_documents', to='documents.institutionaldocumentversion'),
        ),
        migrations.AddConstraint(
            model_name='institutionaldocumentversion',
            constraint=models.UniqueConstraint(fields=('document', 'version_number'), name='unique_document_version_number'),
        ),
        migrations.AddIndex(
            model_name='institutionaldocumentaccesslog',
            index=models.Index(fields=['document', 'action'], name='documents_i_documen_672757_idx'),
        ),
        migrations.AddIndex(
            model_name='institutionaldocumentaccesslog',
            index=models.Index(fields=['accessed_at'], name='documents_i_accesse_710800_idx'),
        ),
        migrations.AddIndex(
            model_name='institutionaldocument',
            index=models.Index(fields=['status'], name='documents_i_status_bb46ba_idx'),
        ),
        migrations.AddIndex(
            model_name='institutionaldocument',
            index=models.Index(fields=['category'], name='documents_i_categor_b4f362_idx'),
        ),
        migrations.AddIndex(
            model_name='institutionaldocument',
            index=models.Index(fields=['related_module'], name='documents_i_related_57e5d7_idx'),
        ),
        migrations.AddIndex(
            model_name='institutionaldocument',
            index=models.Index(fields=['visibility_level'], name='documents_i_visibil_33ff29_idx'),
        ),
        migrations.AddIndex(
            model_name='institutionaldocument',
            index=models.Index(fields=['document_type'], name='documents_i_documen_2a9b3c_idx'),
        ),
        migrations.AddIndex(
            model_name='institutionaldocument',
            index=models.Index(fields=['created_at'], name='documents_i_created_112105_idx'),
        ),
    ]
