# Generated by Django 6.0.6 on 2026-07-06 15:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='core.department')),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='LectureSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monitored_at', models.DateTimeField()),
                ('time_slot', models.CharField(choices=[('08:00-09:00', '8:00 – 9:00'), ('09:00-10:00', '9:00 – 10:00'), ('10:00-11:00', '10:00 – 11:00'), ('11:00-12:00', '11:00 – 12:00'), ('12:00-13:00', '12:00 – 1:00'), ('13:00-14:00', '1:00 – 2:00'), ('14:00-15:00', '2:00 – 3:00'), ('15:00-16:00', '3:00 – 4:00'), ('16:00-17:00', '4:00 – 5:00'), ('17:00-18:00', '5:00 – 6:00'), ('18:00-19:00', '6:00 – 7:00')], max_length=20)),
                ('level', models.CharField(choices=[('100', '100 Level'), ('200', '200 Level'), ('300', '300 Level'), ('400', '400 Level'), ('500', '500 Level'), ('PG', 'Postgraduate')], max_length=10)),
                ('mode', models.CharField(choices=[('physical', 'Physical Classroom'), ('online', 'Online (LMS/Zoom/Meet)'), ('hybrid', 'Hybrid')], max_length=10)),
                ('lecturer_present', models.CharField(choices=[('yes', 'Yes'), ('late', 'Late'), ('no', 'No')], max_length=10)),
                ('actual_duration', models.CharField(choices=[('<30', 'Less than 30 minutes'), ('30-45', '30 – 45 minutes'), ('45-60', '45 – 60 minutes'), ('>60', 'More than 60 minutes')], max_length=10)),
                ('venue', models.CharField(max_length=255)),
                ('held', models.BooleanField()),
                ('explanation', models.TextField(blank=True)),
                ('reason_not_held', models.CharField(blank=True, choices=[('lecturer_absent', 'Lecturer absent'), ('students_absent', 'Students absent'), ('venue_unavailable', 'Venue not available'), ('holiday_strike', 'Public holiday / strike'), ('timetable_clash', 'Time Table clash'), ('technical', 'Technical issues'), ('other', 'Other')], max_length=30)),
                ('estimated_attendance', models.CharField(choices=[('<100', 'Less than 100'), ('100-500', '100 - 500'), ('500-1000', '500 - 1000'), ('>1000', 'More than 1000')], max_length=10)),
                ('classroom_environment_rating', models.PositiveSmallIntegerField()),
                ('teaching_effectiveness_rating', models.PositiveSmallIntegerField()),
                ('quality_concerns', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lecture_sessions', to='courses.course')),
                ('respondent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lecture_monitoring_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-monitored_at'],
            },
        ),
    ]
