# Generated by Django 6.0.6 on 2026-07-06 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='status',
            field=models.CharField(choices=[('student', 'Student'), ('focal_person', 'Focal_Person'), ('principle_officer', 'Principle_Officer'), ('admin', 'Administrator')], default='student', max_length=20),
        ),
    ]
