# Generated by Django 5.2.6 on 2026-07-23 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='status',
            field=models.CharField(choices=[('guest', 'Guest'), ('student', 'Student'), ('staff', 'Staff'), ('focal_person', 'Focal Person'), ('principle_officer', 'Principle Officer'), ('admin', 'Administrator')], default='student', max_length=20),
        ),
    ]
