# Generated by Django 6.0.6 on 2026-07-09 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('update', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='update',
            name='forUser',
            field=models.CharField(default='all', max_length=255),
        ),
    ]
