# Generated by Django 6.0.6 on 2026-07-06 16:07

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccreditationComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('code', models.SlugField(max_length=80, unique=True)),
                ('description', models.TextField(blank=True)),
                ('weight', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('collection_frequency', models.CharField(blank=True, max_length=80)),
                ('information_suppliers', models.TextField(blank=True)),
                ('collection_method', models.TextField(blank=True)),
                ('dashboard_output', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='AccreditationCycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('academic_session', models.CharField(max_length=32)),
                ('semester', models.CharField(blank=True, max_length=32)),
                ('accreditation_body', models.CharField(blank=True, max_length=120)),
                ('accreditation_type', models.CharField(blank=True, max_length=120)),
                ('faculty', models.CharField(blank=True, max_length=160)),
                ('department', models.CharField(blank=True, max_length=160)),
                ('programme', models.CharField(blank=True, max_length=160)),
                ('start_date', models.DateField()),
                ('submission_deadline', models.DateField(blank=True, null=True)),
                ('internal_review_deadline', models.DateField(blank=True, null=True)),
                ('external_visit_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('submission_open', 'Submission Open'), ('internal_review', 'Internal Review'), ('correction_required', 'Correction Required'), ('ready_for_visit', 'Ready for Visit'), ('external_visit_completed', 'External Visit Completed'), ('final_report_approved', 'Final Report Approved'), ('closed', 'Closed')], default='draft', max_length=40)),
            ],
            options={
                'ordering': ['-start_date', 'title'],
            },
        ),
        migrations.CreateModel(
            name='AccreditationMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('code', models.SlugField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('value_type', models.CharField(choices=[('numeric', 'Numeric'), ('text', 'Text'), ('date', 'Date'), ('boolean', 'Boolean'), ('percentage', 'Percentage'), ('score', 'Score')], default='numeric', max_length=20)),
                ('unit', models.CharField(blank=True, max_length=50)),
                ('formula_key', models.SlugField(blank=True, max_length=100, null=True)),
                ('minimum_benchmark', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('warning_threshold', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('danger_threshold', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('required_evidence', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='accreditation.accreditationcomponent')),
            ],
            options={
                'ordering': ['component__code', 'code'],
            },
        ),
        migrations.CreateModel(
            name='ComponentScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('programme', models.CharField(max_length=160)),
                ('score', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('status', models.CharField(choices=[('good', 'Good'), ('warning', 'Warning'), ('critical', 'Critical'), ('no_data', 'No Data')], default='no_data', max_length=20)),
                ('metrics', models.JSONField(blank=True, default=dict)),
                ('calculated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('calculated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='accreditation.accreditationcomponent')),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='component_scores', to='accreditation.accreditationcycle')),
            ],
            options={
                'ordering': ['component__code'],
            },
        ),
        migrations.CreateModel(
            name='EarlyWarningAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('programme', models.CharField(max_length=160)),
                ('trigger_type', models.CharField(max_length=80)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('open', 'Open'), ('acknowledged', 'Acknowledged'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('escalated', 'Escalated')], default='open', max_length=20)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('component', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts', to='accreditation.accreditationcomponent')),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='accreditation.accreditationcycle')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CorrectiveAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('programme', models.CharField(max_length=160)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('assigned_unit', models.CharField(blank=True, max_length=160)),
                ('responsible_officer', models.CharField(blank=True, max_length=160)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('progress_percentage', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('status', models.CharField(choices=[('open', 'Open'), ('assigned', 'Assigned'), ('in_progress', 'In Progress'), ('submitted_for_validation', 'Submitted for Validation'), ('validated', 'Validated'), ('verified', 'Verified'), ('rejected', 'Rejected'), ('overdue', 'Overdue'), ('escalated', 'Escalated'), ('closed', 'Closed')], default='open', max_length=40)),
                ('completion_evidence', models.FileField(blank=True, null=True, upload_to='accreditation/actions/')),
                ('reviewer_comment', models.TextField(blank=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('component', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='corrective_actions', to='accreditation.accreditationcomponent')),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='corrective_actions', to='accreditation.accreditationcycle')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_actions', to=settings.AUTH_USER_MODEL)),
                ('alert', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='corrective_actions', to='accreditation.earlywarningalert')),
            ],
            options={
                'ordering': ['deadline', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MetricSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('programme', models.CharField(max_length=160)),
                ('submitted_value', models.TextField(blank=True)),
                ('numeric_value', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('text_value', models.TextField(blank=True)),
                ('date_value', models.DateField(blank=True, null=True)),
                ('boolean_value', models.BooleanField(blank=True, null=True)),
                ('source_unit', models.CharField(blank=True, max_length=160)),
                ('reporting_period', models.CharField(max_length=50)),
                ('validation_status', models.CharField(choices=[('pending', 'Pending'), ('validated', 'Validated'), ('rejected', 'Rejected'), ('needs_correction', 'Needs Correction')], default='pending', max_length=30)),
                ('reviewer_comment', models.TextField(blank=True)),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='accreditation.accreditationcomponent')),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='accreditation.accreditationcycle')),
                ('metric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='accreditation.accreditationmetric')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Evidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('programme', models.CharField(max_length=160)),
                ('title', models.CharField(max_length=255)),
                ('evidence_type', models.CharField(blank=True, max_length=80)),
                ('file', models.FileField(upload_to='accreditation/evidence/')),
                ('upload_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('verification_status', models.CharField(choices=[('missing', 'Missing'), ('uploaded', 'Uploaded'), ('under_review', 'Under Review'), ('verified', 'Verified'), ('rejected', 'Rejected'), ('replacement_required', 'Replacement Required')], default='uploaded', max_length=30)),
                ('reviewer_comment', models.TextField(blank=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence', to='accreditation.accreditationcomponent')),
                ('corrective_action', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evidence', to='accreditation.correctiveaction')),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence', to='accreditation.accreditationcycle')),
                ('metric', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evidence', to='accreditation.accreditationmetric')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('submission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evidence', to='accreditation.metricsubmission')),
            ],
            options={
                'ordering': ['-upload_date'],
            },
        ),
        migrations.CreateModel(
            name='PARIResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('programme', models.CharField(max_length=160)),
                ('pari_score', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('classification', models.CharField(choices=[('accreditation_ready', 'Accreditation Ready'), ('moderate_risk', 'Moderate Risk'), ('high_risk', 'High Risk')], max_length=40)),
                ('breakdown', models.JSONField(blank=True, default=list)),
                ('calculated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('calculated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pari_results', to='accreditation.accreditationcycle')),
            ],
            options={
                'ordering': ['-calculated_at'],
            },
        ),
        migrations.CreateModel(
            name='RiskClassification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('programme', models.CharField(max_length=160)),
                ('classification', models.CharField(choices=[('accreditation_ready', 'Accreditation Ready'), ('moderate_risk', 'Moderate Risk'), ('high_risk', 'High Risk')], max_length=40)),
                ('pari_score', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('notes', models.TextField(blank=True)),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_classifications', to='accreditation.accreditationcycle')),
            ],
            options={
                'ordering': ['classification', 'programme'],
            },
        ),
        migrations.AddConstraint(
            model_name='accreditationmetric',
            constraint=models.UniqueConstraint(fields=('component', 'code'), name='unique_accreditation_metric_code'),
        ),
        migrations.AddConstraint(
            model_name='componentscore',
            constraint=models.UniqueConstraint(fields=('cycle', 'programme', 'component'), name='unique_component_score'),
        ),
        migrations.AddIndex(
            model_name='earlywarningalert',
            index=models.Index(fields=['cycle', 'programme', 'status'], name='accreditati_cycle_i_d3f02d_idx'),
        ),
        migrations.AddIndex(
            model_name='earlywarningalert',
            index=models.Index(fields=['trigger_type', 'severity'], name='accreditati_trigger_d181fc_idx'),
        ),
        migrations.AddConstraint(
            model_name='metricsubmission',
            constraint=models.UniqueConstraint(fields=('cycle', 'programme', 'component', 'metric', 'reporting_period'), name='unique_metric_submission_period'),
        ),
        migrations.AddConstraint(
            model_name='pariresult',
            constraint=models.UniqueConstraint(fields=('cycle', 'programme'), name='unique_pari_result'),
        ),
        migrations.AddConstraint(
            model_name='riskclassification',
            constraint=models.UniqueConstraint(fields=('cycle', 'programme'), name='unique_risk_classification'),
        ),
    ]
