# Generated by Django 6.0.6 on 2026-07-07 16:36

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QAActionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action_description', models.TextField()),
                ('expected_completion_date', models.DateField()),
                ('actual_completion_date', models.DateField(blank=True, null=True)),
                ('progress_percentage', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='not_started', max_length=20)),
                ('implementation_notes', models.TextField(blank=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_qa_action_plans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['expected_completion_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QAActionEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='qa_committee/evidence/')),
                ('external_url', models.URLField(blank=True)),
                ('verification_status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('verification_comment', models.TextField(blank=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_qa_evidence', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_qa_evidence', to=settings.AUTH_USER_MODEL)),
                ('action_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence', to='qa_committee.qaactionplan')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QAAuditCycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('review_period_start', models.DateField()),
                ('review_period_end', models.DateField()),
                ('audit_type', models.CharField(choices=[('routine', 'Routine'), ('accreditation_readiness', 'Accreditation Readiness'), ('examination_quality', 'Examination Quality'), ('curriculum_delivery', 'Curriculum Delivery'), ('infrastructure', 'Infrastructure'), ('laboratory', 'Laboratory'), ('student_support', 'Student Support'), ('documentation', 'Documentation'), ('research', 'Research'), ('general', 'General')], default='general', max_length=40)),
                ('target_programme', models.CharField(blank=True, max_length=160)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('ongoing', 'Ongoing'), ('submitted', 'Submitted'), ('reviewed', 'Reviewed'), ('closed', 'Closed')], default='draft', max_length=20)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_qa_audit_cycles', to=settings.AUTH_USER_MODEL)),
                ('target_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='qa_audit_cycles', to='core.department')),
                ('target_faculty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='qa_audit_cycles', to='core.faculty')),
            ],
            options={
                'ordering': ['-review_period_start'],
            },
        ),
        migrations.CreateModel(
            name='QAAuditFinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('finding_code', models.CharField(blank=True, max_length=40, unique=True)),
                ('source_module', models.CharField(choices=[('courses', 'Courses'), ('lectures', 'Lectures'), ('examinations', 'Examinations'), ('accreditation', 'Accreditation'), ('documents', 'Documents'), ('students', 'Students'), ('analytics', 'Analytics'), ('core', 'Core'), ('manual', 'Manual')], default='manual', max_length=40)),
                ('source_record_type', models.CharField(blank=True, max_length=120)),
                ('source_record_id', models.CharField(blank=True, max_length=80)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('staffing', 'Staffing'), ('curriculum', 'Curriculum'), ('examination', 'Examination'), ('infrastructure', 'Infrastructure'), ('laboratory', 'Laboratory'), ('library', 'Library'), ('research', 'Research'), ('student_support', 'Student Support'), ('documentation', 'Documentation'), ('governance', 'Governance'), ('other', 'Other')], default='other', max_length=40)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20)),
                ('risk_level', models.CharField(choices=[('low', 'Low'), ('moderate', 'Moderate'), ('high', 'High')], default='moderate', max_length=20)),
                ('evidence_summary', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('under_review', 'Under Review'), ('resolved', 'Resolved'), ('dismissed', 'Dismissed')], default='open', max_length=20)),
                ('audit_cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='findings', to='qa_committee.qaauditcycle')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_qa_findings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QACommittee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('scope_type', models.CharField(choices=[('department', 'Department'), ('faculty', 'Faculty'), ('programme', 'Programme'), ('institutional', 'Institutional'), ('unit', 'Unit')], max_length=30)),
                ('programme', models.CharField(blank=True, max_length=160)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('dissolved', 'Dissolved')], default='active', max_length=20)),
                ('date_constituted', models.DateField()),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_qa_committees', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='qa_committees', to='core.department')),
                ('faculty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='qa_committees', to='core.faculty')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='qaauditcycle',
            name='committee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_cycles', to='qa_committee.qacommittee'),
        ),
        migrations.CreateModel(
            name='CommitteeMeeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('meeting_type', models.CharField(choices=[('regular', 'Regular'), ('emergency', 'Emergency'), ('accreditation_review', 'Accreditation Review'), ('audit_review', 'Audit Review'), ('quarterly_review', 'Quarterly Review')], default='regular', max_length=40)),
                ('scheduled_date', models.DateTimeField()),
                ('held_date', models.DateTimeField(blank=True, null=True)),
                ('venue', models.CharField(blank=True, max_length=255)),
                ('agenda', models.TextField(blank=True)),
                ('minutes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('held', 'Held'), ('cancelled', 'Cancelled'), ('postponed', 'Postponed')], default='scheduled', max_length=20)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_committee_meetings', to=settings.AUTH_USER_MODEL)),
                ('committee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meetings', to='qa_committee.qacommittee')),
            ],
            options={
                'ordering': ['-scheduled_date'],
            },
        ),
        migrations.CreateModel(
            name='QACommitteeDataReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('review_title', models.CharField(max_length=255)),
                ('source_module', models.CharField(max_length=80)),
                ('source_endpoint_or_model', models.CharField(blank=True, max_length=180)),
                ('target_programme', models.CharField(blank=True, max_length=160)),
                ('review_period_start', models.DateField()),
                ('review_period_end', models.DateField()),
                ('extracted_summary', models.JSONField(blank=True, default=dict)),
                ('validation_status', models.CharField(choices=[('pending', 'Pending'), ('valid', 'Valid'), ('questionable', 'Questionable'), ('invalid', 'Invalid')], default='pending', max_length=20)),
                ('reviewer_comment', models.TextField(blank=True)),
                ('committee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_reviews', to='qa_committee.qacommittee')),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qa_data_reviews', to=settings.AUTH_USER_MODEL)),
                ('target_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='qa_data_reviews', to='core.department')),
                ('target_faculty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='qa_data_reviews', to='core.faculty')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QACommitteeMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('chairperson', 'Chairperson'), ('secretary', 'Secretary'), ('member', 'Member'), ('qa_focal_person', 'QA Focal Person'), ('observer', 'Observer')], max_length=30)),
                ('designation', models.CharField(blank=True, max_length=160)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('committee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='qa_committee.qacommittee')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qa_committee_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['committee', 'role', 'user__username'],
            },
        ),
        migrations.CreateModel(
            name='CommitteeMeetingAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendance_status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('excused', 'Excused')], max_length=20)),
                ('remarks', models.TextField(blank=True)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance', to='qa_committee.committeemeeting')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meeting_attendance', to='qa_committee.qacommitteemember')),
            ],
        ),
        migrations.CreateModel(
            name='QACommitteeReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('report_type', models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('annual', 'Annual'), ('accreditation_readiness', 'Accreditation Readiness'), ('special', 'Special')], max_length=40)),
                ('reporting_period_start', models.DateField()),
                ('reporting_period_end', models.DateField()),
                ('summary', models.TextField()),
                ('key_findings', models.TextField(blank=True)),
                ('recommendations_summary', models.TextField(blank=True)),
                ('action_plan_summary', models.TextField(blank=True)),
                ('qacei_score', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('reviewed', 'Reviewed'), ('approved', 'Approved')], default='draft', max_length=20)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('audit_cycle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='qa_committee.qaauditcycle')),
                ('committee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='qa_committee.qacommittee')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_qa_reports', to=settings.AUTH_USER_MODEL)),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_qa_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-reporting_period_start'],
            },
        ),
        migrations.CreateModel(
            name='QARecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('recommendation_text', models.TextField()),
                ('responsible_unit_type', models.CharField(choices=[('department', 'Department'), ('faculty', 'Faculty'), ('programme', 'Programme'), ('directorate', 'Directorate'), ('registry', 'Registry'), ('bursary', 'Bursary'), ('library', 'Library'), ('works', 'Works'), ('student_affairs', 'Student Affairs'), ('other', 'Other')], max_length=40)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=20)),
                ('due_date', models.DateField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('in_progress', 'In Progress'), ('implemented', 'Implemented'), ('verified', 'Verified'), ('rejected', 'Rejected'), ('overdue', 'Overdue')], default='pending', max_length=20)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_qa_recommendations', to=settings.AUTH_USER_MODEL)),
                ('audit_cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='qa_committee.qaauditcycle')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_qa_recommendations', to=settings.AUTH_USER_MODEL)),
                ('finding', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recommendations', to='qa_committee.qaauditfinding')),
                ('responsible_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='qa_recommendations', to='core.department')),
                ('responsible_faculty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='qa_recommendations', to='core.faculty')),
            ],
            options={
                'ordering': ['due_date', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='qaactionplan',
            name='recommendation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_plans', to='qa_committee.qarecommendation'),
        ),
        migrations.AddConstraint(
            model_name='qacommitteemember',
            constraint=models.UniqueConstraint(fields=('committee', 'user'), name='unique_committee_user_membership'),
        ),
        migrations.AddConstraint(
            model_name='committeemeetingattendance',
            constraint=models.UniqueConstraint(fields=('meeting', 'member'), name='unique_meeting_member_attendance'),
        ),
    ]
