# Generated by Django 6.0.6 on 2026-07-06 17:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LecturerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_id', models.CharField(max_length=30, unique=True)),
                ('rank', models.CharField(blank=True, max_length=100)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lecturers', to='core.department')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lecturer_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AssessmentReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_session', models.CharField(max_length=20)),
                ('semester', models.CharField(blank=True, max_length=20)),
                ('presents_content_actively', models.PositiveSmallIntegerField()),
                ('covers_content_within_timeframe', models.PositiveSmallIntegerField()),
                ('gives_useful_assignments', models.PositiveSmallIntegerField()),
                ('impressive_comportment', models.PositiveSmallIntegerField()),
                ('punctual_at_lectures', models.PositiveSmallIntegerField()),
                ('available_for_consultation', models.PositiveSmallIntegerField()),
                ('clear_on_concepts', models.PositiveSmallIntegerField()),
                ('links_theory_to_practice', models.PositiveSmallIntegerField()),
                ('encourages_participation', models.PositiveSmallIntegerField()),
                ('provides_assignment_feedback', models.PositiveSmallIntegerField()),
                ('teaches_per_course_outline', models.PositiveSmallIntegerField()),
                ('teaches_class_regularly', models.PositiveSmallIntegerField()),
                ('updates_course_content', models.PositiveSmallIntegerField()),
                ('uses_real_life_examples', models.PositiveSmallIntegerField()),
                ('appears_neatly', models.PositiveSmallIntegerField()),
                ('uses_varied_teaching_methods', models.PositiveSmallIntegerField()),
                ('uses_technology_innovatively', models.PositiveSmallIntegerField()),
                ('included_in_dossier', models.BooleanField(default=False)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lecturer_assessments', to='courses.course')),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lecturer_assessments_submitted', to=settings.AUTH_USER_MODEL)),
                ('lecturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_reports', to='lecturers.lecturerprofile')),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
    ]
